language: python
python:
- 3.6.3
script:
- python test.py
deploy:  
  provider: heroku  
  app: html-medium
  on:    
    branch: master
  api_key:
    secure: CbOHmrJJ9ODqa1Q2WjCgqifaVlsNR+SOBevp82yKNI/FUiU0wi0YbBCNw3kV2MGP/CwIeN/SoaMAjh/O6fLOa8HiHI7n6/2b2rU+gpTqbzk4Submp8drhiiMAbgBjoYUrWNOhoOBK+kmnrt/AOQnjIe90dx5Y5ufQ/j0+3YsXNMV6bhjn8i3CoZzCGbleFl//ZEAkMRHoNgf6l/nWt2H/rKdJ45Cm+bCDvk3+M4N07Zytybp/Mc8u56xanCyHZh+jCPwKmcaTcrKaFpqFBdK/GRM/IuBEYRBOKdthuCEgBal/kOlLB9VEhkrqOrqYsbMaXxZa50ZNlcYl5xOhXOzryTtdVQ9YYJf8Gbo1lf1dqj1y1OPx5pU7XPsZaUqHJq33bseIR0vFLnz7An5k+jbYNvBd/Y8knfObIbW0DXAMSe1IQ5Sx6KpzH/t5I2H2XK6vSKSMA/DwfwCLNRMwzVEZ7AgsXevfdmm7Bbi4qtqqhuOw99yrlQj7m9UVqdfjDb1shgtbN1wWbF5ayaeFhIZJbA67wWgvOUc20yiwISfyJ2mYdrYT+IgewwcG7wGAObCLbCz2YtWQe3xu5R6G/nhdLPOjagcbw/a2x/uLPKFq5sp/AbHQcAfTyAODlWL5xCcCgRMbNDXnVp/mxGvHPprhckn+q/c0s0xUMbR42NEQmA=
