language: python
python:
- 3.6.3
script:
- python test.py
deploy:  
  provider: heroku  
  app: html-medium
  on:    
    branch: master
  api_key:
    secure: U2eVG6SkMXHhROHvU11KmqV5sKW64pxb+q1QVbxBMwcIZIgEEaISRL3hmhErn7pYFq/FsJRTHGisE7Spz27rstGgesJjmTiMYSDoA8g+XvaKrLSVaP5eDt3oa8IX5MqhfmsJ8/mafoLIWXrsyu/S5Jmwsu8RrZJ1bLdhoxolfpTwTJg8ApR96eDczpdNE+wzJlvqunqtyse47H+Aj/XdLl6Pz8IVOE8l2RPoUJ+mr4l7UM3KlEwTTj1VFMzlccm3q1Nvf1Gyu2EZEq2c2IUCWqaagWJRHqEL1e4IgCB2xNvsa/3UZkQVyT+qFKA5rjKYETZse/wkRYpdtM/0VYGNecSrHs0SlT+FDAy5i+LMv+zv0E9Zrn/ayesu9uD8B5ZSOS014AIzoM8eJH3uquMGnNLAdKlf0l2Rq28gVFcv8FEu3Vb4IxgeWV1uNe/yG0nvyEqqs8uVIm8PKo9GUb3rvTgswFZRmayml/X4rEY/80+ifagStWEihI9dCBZ8QDDb2pEk9Ogr4NHazdi9RKE8fsJTTZICBmBvisQTDiMploX9nubQXfwj5bC+4BZNhNkk/Tv7DNLRc20VFtI3B9kz3N0XUrE8Tj8yvqJYxCvHkrqscX1bmkXpWeZ5INEJ6m4yyjkZr+SLc1tvF0dIeBZ/f7e0idom0+xsxJQgH5QWe1I=
