language: python
python:
- 3.6.3
script:
- python test.py
deploy:  
  provider: heroku  
  app: html-medium
  on:    
    branch: master
  api_key:
    secure: iqfyestHnVBZU2jxKqsAn0F+STg0FR7wZQcCD2NQ7xbHljsul7E5B7DdJSDSYLUYimF23P3DbjSuT3wsYQM6qZ9+5fU8MDBIAy53SAqiXa7+ZR2ENKbswW7n8wkR+jg3eBdCXkuytkE9/SgvM2+oztrFnw5yFxzHhpKuqvyzKDRoSUZENvotUTPRUMzxjvMzfgWEzJ36xLum/my8ZGq6/84h1lUPccGILJfs6UcX6yrTew6wV0aDIIbyCfMJpB9fYBzNuD1DVnOPF+agnAMExoKEzHcWbfXva9i1oRS8Uc5zP8NWf3Hvm+NvoGPmIieqV244udFw0zVm/2pXg19WYTGes3aB4sQBzJNXjsb4NWF8i594RYZ11EWo8tN2RNR1NmBc+hQKf9GQgr3n1BJOd4JDMoC9O/WVvynj50oY9ZaUfbTzCc5qSpWulhbvQDrEkklByBr7zdcYWzNEOyt8ofhlkmavmgHNZb1UNxxNWl06u7UvLQ4Cxv4SqExtHYubJtler+PHgBYoGtzUVck3XMQwJ1HjlzhoJ4YlmrnwTm+wXsrTyfe5h0J/o4R9ybhSdx/uvf2kB8DhzIPvPVkeoYdtR9OxxXgdZwat5OwDJitHzlbwZD/rgCOM89zMbo0OyUHeq9v5gFbKyX8fGhmb/N6hi1BgVPDUcmLO1th8Ofk=
